### ISSUE TITLE
Set up a front-end JS framework

### ISSUE THREAD

**Issue by MarkKoz** [Comp-490-SeniorProject/site#7]
Given the complexity of our app, it seems to make sense to rely on a front-end framework. I am leaning towards Angular, since it uses TypeScript, and TypeScript makes JS a lot more bearable for me. Apart from that, I have no experience with Angular or any other framework (React, Vue, etc.). Does anyone else want to express thoughts on which framework to use?

There's a tutorial [here](https://www.bezkoder.com/django-angular-12-crud-rest-framework/) for how to set up Angular with Django. I'm not sure if we need webpack, but there's also [this](https://www.valentinog.com/blog/webpack-django/) article about how to use it (and it links to some other tutorials). It's unclear yet if we need to worry about large bundles and having to split them up. It also brings up some ideas for how to design the project. I think option 1 seems the simplest:

> Option 1. React/Vue/Whatever in its own frontend Django app: load a single HTML template and let JavaScript manage the frontend.

The author seems to have an entire book on this subject, which may be worth a read. It's more focused on React and Vue unfortunately.

**Comment by mndzamel** [comment]
I also think Angular would be a good choice. I have to use the framework for another class project so I'll have a bit of experience.
