### ISSUE TITLE
Configure security headers

### ISSUE THREAD

**Issue by MarkKoz** [Comp-490-SeniorProject/site#8]
For good practice, we should strive to get a good score on https://securityheaders.com/. To attain that goal, one of the things we need to do is set up a CSP and some other security headers. The `secure.py` library makes this very convenient since it has [integration with Django](https://secure.readthedocs.io/en/latest/frameworks.html#django). I suppose we want the CSP as strict as possible while still ensuring the website functions. We may need to adjust it as we progress in development, but we need to start somewhere.

**Comment by alinaah** [comment]
Please see attached what has been presented on 10.21.2021.Research is still in progress.

[Presentation_CSP_10.21.2021.docx](https://github.com/Comp-490-SeniorProject/site/files/7445970/Presentation_CSP_10.21.2021.docx)
