### ISSUE TITLE
Set up linting for JS

### ISSUE THREAD

**Issue by MarkKoz** [Comp-490-SeniorProject/site#9]
Similar to the extant linting tools that are configured for Python, we'll want linting for JS code to ensure it's consistent, readable, and following good practices. How exactly linting is set up will depend on which JS framework we go with, particularly if we use JS or TS. For a previous project, I used `eslint` with `prettier` as seen [here](https://github.com/COMP-380-6/recipes/blob/main/.pre-commit-config.yaml#L11-L25). The `.eslintrc` and `.prettierrc` are also in that repo.

**Comment by alinaah** [comment]
Please check out:
https://github.com/Comp-490-SeniorProject/site/commit/374b8a765d1aa3d14cdb0083e642470e9cab5003

**Comment by MarkKoz** [comment]
You need to create a pull request. This issue isn't complete until your pull request gets merged into the main branch.
